apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  labels:
    resource: root
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
spec:
  project: default
  source: 
    repoURL: https://github.com/Mathpro1412/platform-k8s-app.git
    targetRevision: main
    path: system
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd