apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nong-kai-api-prod
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
spec:
  project: default
  source:
    repoURL: https://github.com/Mathpro1412/platform-k8s-app-overlays.git
    targetRevision: main
    path: apps/prod
  destination:
    name: in-cluster
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true