apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nong-kai-api-prod
spec:
  project: default
  source:
    repoURL: https://github.com/Mathpro1412/platform-k8s-app-config-prod.git
    targetRevision: main
    path: manifests
  destination:
    name: in-cluster
    namespace: prod
  syncPolicy:
    automated:
      prune: true