apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nong-kai-api-nonprod
spec:
  project: default
  source:
    repoURL: https://github.com/Mathpro1412/platform-k8s-app-overlays.git
    targetRevision: main
    path: apps/nonprod
  destination:
    name: in-cluster
    namespace: nonprod
  syncPolicy:
    automated:
      prune: true