apiVersion: v1
kind: ConfigMap
metadata:
    name: argocd-notifications-cm
    namespace: argocd
data:
    service.webhook.discord: |
        url: https://discord.com/api/webhooks/1373677287006011586/tWgjgjxMemL1PiEE-Oj2Ws48QajYdnHIpcwmbC-DZCOYeclItnwMOZa5Lh1WY2m7txk0
        headers:
            - name: Content-Type
              value: application/json

    template.app-sync-succeeded: |
        webhook:
            discord:
                method: POST # one of: GET, POST, PUT, PATCH. Default value: GET
                body: |
                    {
                        "username": ": "{{.app.metadata.name}}",
                        "content": " Application {{.app.metadata.name}} is now running new version of deployments manifests.
                            url: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
                            context: continuous-delivery/{{.app.metadata.name}}
                        "
                    }

    trigger.on-sync-succeeded: |
        - description: Application syncing has succeeded
          send:
          - app-sync-succeeded
          when: app.status.operationState.phase in ['Succeeded']